### ISSUE TITLE
Constructor for EntityGenerator.

### ISSUE THREAD

**Issue by rrekapalli** [ibonn/dammy#3]
Hi there,

Can we have a constructor for an 'EntityGenerator' class?  

```
from dammy.core import BaseGenerator
import random_address

class Address(BaseGenerator):
    def __init__(self):
        super(Address, self).__init__('VARCHAR(100)')

    def generate_raw(self, dataset=None):
        return random_address.random_address.real_random_address()
```

Let's say, I would like to assign properties of the above address to individual fields of a Person class like below:

```
from dammy import EntityGenerator
class Person(EntityGenerator):
    first_name = RandomName().upper()
    address = Address() # This is the class previously implemented
    Line1 = address.Street_number()
    Line2 = address.Street_Name()
    City = address.City()

for i in range(0, 10):
    print(Person())
```

However, when I try this, I am getting some issues like it's showing a generic object string rather than the actual value!  I am trying to see if there's way that I can individually refer a created object's properties.  Or as another alternative, can we have supporting methods in the 'class Person(EntityGeenrator):'  that would create an Address object in the constructor and initialize with a value,  and then we can refer the individual attributes like shown above (Line1, Line2, City etc)? 

Hope this makes sense.  Please do let me know in case you need any further details. 

Thanks,
Raja

**Comment by ibonn** [comment]
Hello @rrekapalli,
This is currently possible to do in some manner, but perhaps the API would need to be improved to get the results you want to get in a simpler way.

Currently you can create an `AttributeGetter` class and assign the address values to class variables each time you generate a new address, so that the AttributeGetter can access them. I know this can cause some problems if you have more than one address per person (the values of the second address would overwrite those of the first one) and if that is your case, this is currently the best you can get without having to wait for that bug to be fixed in the next version.

Anyway, here is the implementation of how to solve your problem below

```python
import random_address
from dammy import EntityGenerator
from dammy.core import BaseGenerator
from dammy.stdlib import RandomName


class AttributeGetter(BaseGenerator):
    def __init__(self, obj, attr):
        self.obj = obj
        self.attr = attr

    def generate_raw(self, dataset=None):
        return getattr(self.obj, self.attr)


class Address(BaseGenerator):

    _city = None
    _street_name = None
    _street_number = None

    def __init__(self):
        super(Address, self).__init__('VARCHAR(100)')

    def generate_raw(self, dataset=None):
        address = random_address.random_address.real_random_address()
        Address._city = address['city']
        Address._street_name = address['address1']
        Address._street_number = address['address2']
        return address

    @classmethod
    def city(cls):
        return AttributeGetter(cls, '_city')

    @classmethod
    def street_name(cls):
        return AttributeGetter(cls, '_street_name')

    @classmethod
    def street_number(cls):
        return AttributeGetter(cls, '_street_number')


class Person(EntityGenerator):
    first_name = RandomName().upper()
    address = Address()  # This is the class previously implemented
    Line1 = address.street_name()
    Line2 = address.street_number()
    City = address.city()


for i in range(0, 10):
    print(Person())

```

Hope this helps
